export default function() {
    return [{
            EnglishName: 'Quran',
            ArabicName: 'القرٱن ',
            meaning: 'Recite',
            reference: 'Recite',
            source: '(2:185) (4:82) (6:19) (7:204) (9:111)(10:37) (10:61) (15:87) (16: 98) (17:9)(17:78) (17:82) (17:88) (20:1-2) (20:113)(25:32) (27:6) (27:76) (27:92) (38:1)(39:27) (46:29) (50:1) (54:17) (55:1-2) ((56:77)) (59:21) (72:1-2) (73:4) (73:20)',
            tooltip: {
                '2:185': "The month of Ramadhan [is that] in which was revealed the Qur'an, a guidance for the people and clear proofs of guidance and criterion. So whoever sights [the new moon of] the month, let him fast it; and whoever is ill or on a journey - then an equal number of other days. Allah intends for you ease and does not intend for you hardship and [wants] for you to complete the period and to glorify Allah for that [to] which He has guided you; and perhaps you will be grateful.",
                '4:82': "Then do they not reflect upon the Qur'an? If it had been from [any] other than Allah, they would have found within it much contradiction.",
                '7:204': "So when the Qur'an is recited, then listen to it and pay attention that you may receive mercy.",
                '9:111': "Indeed, Allah has purchased from the believers their lives and their properties [in exchange] for that they will have Paradise. They fight in the cause of Allah, so they kill and are killed. [It is] a true promise [binding] upon Him in the Torah and the Gospel and the Qur'an. And who is truer to his covenant than Allah ? So rejoice in your transaction which you have contracted. And it is that which is the great attainment.",
                '10:37': "And it was not [possible] for this Qur'an to be produced by other than Allah, but [it is] a confirmation of what was before it and a detailed explanation of the [former] Scripture, about which there is no doubt, from the Lord of the worlds.",
                '15:87': "And We have certainly given you, [O Muhammad], seven of the often repeated [verses] and the great Qur'an.",
                '16: 98': "So when you recite the Qur'an, [first] seek refuge in Allah from Satan, the expelled [from His mercy].",
                '17:9': "Indeed, this Qur'an guides to that which is most suitable and gives good tidings to the believers who do righteous deeds that they will have a great reward.",
                '17:78': "Establish prayer at the decline of the sun [from its meridian] until the darkness of the night and [also] the Qur'an of dawn. Indeed, the recitation of dawn is ever witnessed.",
                '17:82': "And We send down of the Qur'an that which is healing and mercy for the believers, but it does not increase the wrongdoers except in loss.",
                '17:88': "Say, If mankind and the jinn gathered in order to produce the like of this Qur'an, they could not produce the like of it, even if they were to each other assistants.",
                '20:1-2': "Say, If mankind and the jinn gathered in order to produce the like of this Qur'an, they could not produce the like of it, even if they were to each other assistants.",
                '20:113': "And thus We have sent it down as an Arabic Qur'an and have diversified therein the warnings that perhaps they will avoid [sin] or it would cause them remembrance",
                '25:32': "And those who disbelieve say, Why was the Qur'an not revealed to him all at once?Thus [it is] that We may strengthen thereby your heart. And We have spaced it distinctly.",
                '27:6': "And indeed, [O Muhammad], you receive the Qur'an from one Wise and Knowing.",
                '27:92': "And to recite the Qur'an. And whoever is guided is only guided for [the benefit of] himself; and whoever strays - say, I am only [one] of the warners.",
                '38:1': "Sad. By the Qur'an containing reminder...",
                '39:27': "And We have certainly presented for the people in this Qur'an from every [kind of] example - that they might remember.",
                '46:29': "And [mention, O Muhammad], when We directed to you a few of the jinn, listening to the Qur'an. And when they attended it, they said, Listen quietly. And when it was concluded, they went back to their people as warners, ",
                '50:1': "Qaf. By the honored Qur'an...",
                '55:1-2': "The Most MercifulTaught the Qur'an,",
                '54:17': "And We have certainly made the Qur'an easy for remembrance, so is there any who will remember?",
                '56:77': "And We have certainly made the Qur'an easy for remembrance, so is there any who will remember?",
                '59:21': "If We had sent down this Qur'an upon a mountain, you would have seen it humbled and coming apart from fear of Allah . And these examples We present to the people that perhaps they will give thought.",
                '72:1': "Say, [O Muhammad], It has been revealed to me that a group of the jinn listened and said, 'Indeed, we have heard an amazing Qur'an.",
                '73:4': "Or add to it, and recite the Qur'an with measured recitation.",
                '73:20': "Indeed, your Lord knows, [O Muhammad], that you stand [in prayer] almost two thirds of the night or half of it or a third of it, and [so do] a group of those with you. And Allah determines [the extent of] the night and the day. He has known that you [Muslims] will not be able to do it and has turned to you in forgiveness, so recite what is easy [for you] of the Qur'an. He has known that there will be among you those who are ill and others traveling throughout the land seeking [something] of the bounty of Allah and others fighting for the cause of Allah . So recite what is easy from it and establish prayer and give zakah and loan Allah a goodly loan. And whatever good you put forward for yourselves - you will find it with Allah . It is better and greater in reward. And seek forgiveness of Allah . Indeed, Allah is Forgiving and Merciful.",
            },
        },
        {
            EnglishName: 'Mubin',
            ArabicName: 'االمبين',
            meaning: 'Luminous',
            source: ' (4:174/175) (5:15) (12:1-2) (27:1) ((43:1-2))',
        },
        {
            EnglishName: 'Al-Kitāb',
            ArabicName: 'الكتاب ',
            meaning: 'The Book ',
            source: ' (4:174/175) (5:15) (12:1-2) (27:1) ((43:1-2))',
        },
        {
            EnglishName: 'Karīm',
            ArabicName: 'الكريم  ',
            meaning: 'Honourable, Noble',
            source: '((56:77))',
        },
        {
            EnglishName: 'KalāmAllāh',
            ArabicName: 'كلام الله   ',
            meaning: 'The Word of Allāh',
            source: '((9:6))',
        },
        {
            EnglishName: 'Nūr',
            ArabicName: 'النور  ',
            meaning: 'Sacred Light',
            source: '((4:174/175)) (7:157) (64:8)',
        },
        {
            EnglishName: 'Hudā',
            ArabicName: 'الهدى  ',
            meaning: 'Right Guidance',
            source: '(2:1-2) (2:97) (2:185) (3:138) (7:52)(7:203) (10:57) (16:89) (16:102) ((27:77))(45:20)',
        },
        {
            EnglishName: 'Rahma',
            ArabicName: 'الرحمان  ',
            meaning: 'Mercy',
            source: '(7:52) (16:64) (17:82) ((27:77)) (31:3)',
        },
        {
            EnglishName: 'Al-Furqān',
            ArabicName: 'الفرقان   ',
            meaning: 'The Criterion of Judgement',
            source: '(2:185)(3:4) ((25:1))',
        },
        {
            EnglishName: 'Dhikr',
            ArabicName: ' الذكر ',
            meaning: 'Remembrance, Reminder',
            source: ' (3:58) (7:1-2) (12:104) (15:9) (16:44)(20:99)(21:24) ((21:50)) (36:11) (36:69)(41:41)(43:5)',
        },
        {
            EnglishName: 'Mubārak',
            ArabicName: 'المبارك  ',
            meaning: 'Blessed',
            source: ' (6:92)(6:155) ((21:50)) (38:29)',
        },
        {
            EnglishName: 'Alī',
            ArabicName: 'العلي  ',
            meaning: 'Exalted ',
            source: '((43:4))',
        },
        {
            EnglishName: 'Hikma',
            ArabicName: ' الحكمة ',
            meaning: 'Perfect Wisdom',
            source: '((54:5))',
        },
        {
            EnglishName: 'Hakīm',
            ArabicName: ' الحكيم ',
            meaning: 'Full of Wisdom',
            source: '((10:1)) (31:1-2) (36:1-2) (43:4)',
        },
        {
            EnglishName: 'Muhaymin',
            ArabicName: ' المهيمن ',
            meaning: 'Guardian, Witness',
            source: '((5:48)) ',
        },
        {
            EnglishName: 'Musaddiq',
            ArabicName: ' المصدق ',
            meaning: 'Confirming Scripture',
            source: '(2:91) (3:3) ((5:48)) (6:92) (35:31)(46:12) (46:30)',
        },
        {
            EnglishName: 'Hablillāh',
            ArabicName: ' حبل الله ',
            meaning: 'The rope of Allāh ',
            source: '((3:103))',
        },
        {
            EnglishName: 'Sirāt ul Mustaqīm',
            ArabicName: '  الصراط المستقيم ',
            meaning: 'The Straight Path',
            source: ' ((6:153))',
        },
        {
            EnglishName: 'Qayyim',
            ArabicName: ' القيم  ',
            meaning: 'Straight Guidance',
            source: '((18:2))',
        },
        {
            EnglishName: 'Qawl',
            ArabicName: ' القول ',
            meaning: 'Word of Allāh',
            source: '(28:51) ((86:13))',
        },
        {
            EnglishName: 'Fasl',
            ArabicName: ' الفصل  ',
            meaning: 'The Criterion of Judgement',
            source: '((86:13))',
        },
        {
            EnglishName: 'Nabaunāazim',
            ArabicName: ' النبأالعظيم ',
            meaning: 'Supreme Message',
            source: '(38:67) ((78:1-2))',
        },
        {
            EnglishName: 'Mathānī',
            ArabicName: 'المثاني   ',
            meaning: 'Oft-repeated',
            source: '((39:23))',
        },
        {
            EnglishName: 'Mutashābih',
            ArabicName: 'المتشابه  ',
            meaning: 'Consistent in itself',
            source: '((39:23))',
        },
        {
            EnglishName: 'Tanzīl',
            ArabicName: 'التنزيل  ',
            meaning: 'The Final Revelation Sent by Allāh',
            source: '(2:4) (2:23) (3:84) (4:166) (5:83)(17:105)(17:106) 20:4) ((26:192-194)) (36:5)(41:1-2) (41:42) (56:80) (97:1)',
        },
        {
            EnglishName: 'Rūh',
            ArabicName: 'الروح  ',
            meaning: 'The Final Revelation',
            source: '((42:52)) ',
        },
        {
            EnglishName: 'Wahy',
            ArabicName: 'الوحي  ',
            meaning: 'The Criterion of Judgement',
            source: '(4:163) (10:109) ((21:45)) (53:4)',
        },
        {
            EnglishName: 'Arabī',
            ArabicName: ' العربي ',
            meaning: 'In Arabic',
            source: ' ((12:2)) (13:37) (26:195) (41:3) (42:7)(43:3)',
        },
        {
            EnglishName: 'Basāir',
            ArabicName: 'االبشير  ',
            meaning: 'Eye-opening evidences',
            source: '',
        },
        {
            EnglishName: 'Bayān',
            ArabicName: 'البيان   ',
            meaning: 'The Final  Statement',
            source: '',
        },
        {
            EnglishName: 'Ilm',
            ArabicName: 'العلم  ',
            meaning: 'Ultimate Knowledge',
            source: '(2:120) ((2:145))',
        },
        {
            EnglishName: 'Haqq',
            ArabicName: 'الحق  ',
            meaning: 'Truth, True',
            source: ' ((3:62)) (10:108) (13:1) (13:19) (28:53)(34:6) (35:31) (47:2) (57:16) (69:51)',
        },
        {
            EnglishName: 'Hādī',
            ArabicName: 'الهادي  ',
            meaning: 'Guide',
            source: '((17:9)) (46:30) (72:2)',
        },
        {
            EnglishName: 'Ajab',
            ArabicName: ' العجب ',
            meaning: 'Wonderful',
            source: '((72:1))',
        },
        {
            EnglishName: 'Tadhkira',
            ArabicName: '  ',
            meaning: 'Admonition, Reminder',
            source: '(20:3) ((69:48)) (74:54)',
        },
        {
            EnglishName: 'Urwatulwuthqa',
            ArabicName: ' العروة الوثقى ',
            meaning: 'The Firm Handhold',
            source: '((2:256))',
        },
        {
            EnglishName: 'Sidq',
            ArabicName: 'الصدق  ',
            meaning: 'Truth',
            source: '(39:32) ((39:33))',
        },
        {
            EnglishName: 'Adl',
            ArabicName: ' العدل  ',
            meaning: 'Justice',
            source: '((6:115))',
        },
        {
            EnglishName: 'AmrAllāh',
            ArabicName: ' أمر الله  ',
            meaning: 'The Commandment of Allāh',
            source: '((65:5))',
        },
        {
            EnglishName: 'Bushrā',
            ArabicName: ' البشرى  ',
            meaning: 'Glad tidings',
            source: '((2:97)) (16:102) (27:2) (46:12)',
        },
        {
            EnglishName: 'Majīd',
            ArabicName: ' المجيد  ',
            meaning: 'Glorious',
            source: '(50:1)((85:21-22))',
        },
        {
            EnglishName: 'Zabūr',
            ArabicName: ' الزبر  ',
            meaning: 'The Criterion of Judgement',
            source: '((21:105))',
        },
        {
            EnglishName: 'Bashīr',
            ArabicName: 'البشير   ',
            meaning: 'Herald of glad tidings',
            source: '(17:9) ((41:4))',
        },
        {
            EnglishName: 'Nadhīr',
            ArabicName: ' الندير  ',
            meaning: 'Warner',
            source: '((41:4))',
        },
        {
            EnglishName: 'Azīz',
            ArabicName: 'العزيز  ',
            meaning: 'Mighty',
            source: '((41:41)',
        },
        {
            EnglishName: 'Balāgh',
            ArabicName: 'البلاغ  ',
            meaning: 'Sufficient Message',
            source: '((14:52)) (21:106)',
        },
        {
            EnglishName: 'Qasas',
            ArabicName: 'القصص',
            meaning: 'Narratives',
            source: ' ((12:3))',
        },
        {
            EnglishName: 'Suhuf',
            ArabicName: 'الصحف  ',
            meaning: 'Scriptures',
            source: '((80:13)) (98:2) ',
        },
        {
            EnglishName: 'Mukarrama',
            ArabicName: 'المكرمة   ',
            meaning: 'Honoured',
            source: '((80:13)) ',
        },
        {
            EnglishName: 'Marfūa',
            ArabicName: ' المعرفة  ',
            meaning: 'Exalted',
            source: ' ((80:14))',
        },
        {
            EnglishName: 'Mutahhara',
            ArabicName: 'المكرمة  ',
            meaning: 'Kept Pure',
            source: '((80:14)) (98:2)',
        },
    ];
}