let store99names = [{
        EnglishName: 'Allaah',
        ArabicName: 'اﻟﻠﻪ  ',
        meaning: 'God',
        evidence: 'In the name of Allah , the Entirely Merciful, the Especially Merciful. [1:1]',
    },
    {
        EnglishName: 'Al-Ahad',
        ArabicName: 'اﻷﺣَﺪ',
        meaning: 'The One/Unique',
        evidence: 'Say,  He is Allah , One  [112:1]',
    },

    {
        EnglishName: "Al-A'laa",
        ArabicName: 'الأعْلَى ',
        meaning: 'The Most Exalted/ High',
        evidence: 'Exalt the name of your Lord, the Most High [87:1]',
    },
    {
        EnglishName: 'Al-Ilaah',
        ArabicName: 'اﻹﻟﻪ ',
        meaning: 'The One Who Alone Deserves to be Worshiped',
        evidence: 'And your god is one God… [2:163]',
    },
    {
        EnglishName: 'Al-Akram',
        ArabicName: 'اﻷﻛْﺮَﻡ',
        meaning: 'The Most Generous',
        evidence: 'Recite, and your Lord is the most Generous ',
    },
    {
        EnglishName: 'Al Awwal',
        ArabicName: 'اﻷﻭَّﻝ  ',
        meaning: 'The First',
        evidence: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing. [57:3]',
    },
    {
        EnglishName: 'Al-Aakhir',
        ArabicName: 'اﻵﺧِﺮ',
        meaning: 'The Last',
        evidence: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing. [57:3]',
    },
    {
        EnglishName: 'Adh-Dhaahir',
        ArabicName: 'اﻟﻈﺎﻫِﺮ',
        meaning: 'The Most High',
        evidence: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing. [57:3]',
    },
    {
        EnglishName: 'Al-Baatin',
        ArabicName: 'اﻟﺒَﺎﻃِﻦ ',
        meaning: 'The Most Near',
        evidence: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing. [57:3]',
    },
    {
        EnglishName: 'Al-Baari',
        ArabicName: ' اﻟﺒﺎﺭِﺉ ',
        meaning: 'The Originator',
        evidence: 'He is Allah , the Creator, the Inventor (originator), the Fashioner… [59:24]',
    },
    {
        EnglishName: 'Al-Barr',
        ArabicName: 'ٱلْبَرُّ',
        meaning: 'The Most Kind',
        evidence: '…Indeed, it is He who is the Beneficent (Most Kind), the Merciful. [52:28]',
    },
    {
        EnglishName: 'Al-Baseer',
        ArabicName: 'اﻟﺒَﺼِﻴﺮ',
        meaning: 'The All Seeing',
        evidence: '…Indeed, He is the Hearing, the Seeing. ',
    },
    {
        EnglishName: 'At-Tawwaab',
        ArabicName: 'اﻟﺘَّﻮَّاﺏ ',
        meaning: 'The One Who Accepts the repentance',
        evidence: '…Indeed, it is He who is the Accepting of repentance, the Merciful. [2:37] ',
    },
    {
        EnglishName: 'Al-Jabbaar ',
        ArabicName: 'اﻟﺠَﺒَّﺎﺭ ',
        meaning: 'The Compeller',
        evidence: 'He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Bestower of Faith, the Oevidenceer (dominant), the Exalted in Might, the Compeller, the Superior… [59:23] ',
    },
    {
        EnglishName: 'Al-Haafiz ',
        ArabicName: 'اﻟﺤﺎﻓِﻆ ',
        meaning: 'The Protector',
        evidence: '…But Allah is the best guardian… [12:64] ',
    },
    {
        EnglishName: 'Al-Haseeb',
        ArabicName: ' اﻟﺤَﺴِﻴﺐ ',
        meaning: 'The Sufficient/ Ever-Reckoner',
        evidence: '…Indeed, Allah is ever, over all things, an Accountant (Ever-Reckoner). [4:86] ',
    },
    {
        EnglishName: 'Al-Hafeez',
        ArabicName: 'اﻟﺤَﻔِﻴﻆ',
        meaning: 'The Preserver',
        evidence: '…And your Lord, over all things, is Guardian (Preserver). [34:21] ',
    },
    {
        EnglishName: 'Al-Hafee',
        ArabicName: 'الحَفِي',
        meaning: 'The Benevolent/ Ever-Hospitable',
        evidence: '',
    },
    {
        EnglishName: 'Al-Haqq',
        ArabicName: ' ٱلْحَقُّ',
        meaning: 'The Truth',
        evidence: '',
    },
    {
        EnglishName: 'Al-Mubeen',
        ArabicName: ' اﻟﻤُﺒِﻴﻦ ',
        meaning: 'The Evident',
        evidence: '',
    },
    {
        EnglishName: 'Al-Hakeem',
        ArabicName: 'اﻟﺤَﻜِﻴﻢ',
        meaning: 'The All-Wise',
        evidence: '',
    },
    {
        EnglishName: 'Al-Haleem',
        ArabicName: 'اﻟﺤَﻠِﻴﻢ',
        meaning: 'The Forbearing',
        evidence: '',
    },
    {
        EnglishName: 'Al-Hameed',
        ArabicName: 'اﻟﺤَﻤِﻴﺪ. ',
        meaning: 'The Praiseworthy',
        evidence: '',
    },
    {
        EnglishName: 'Al-Hayy',
        ArabicName: 'الحَي  ',
        meaning: 'The Ever Living',
        evidence: '',
    },
    {
        EnglishName: 'Al-Qayyoom',
        ArabicName: '  ٱلْقَيُّومُ    ',
        meaning: 'The Self Sustaining',
        evidence: '',
    },
    {
        EnglishName: 'Al-Khabeer',
        ArabicName: 'اﻟﺨَﺒِﻴﺮ',
        meaning: 'The Fully Aware',
        evidence: '',
    },
    {
        EnglishName: 'Al-Khaaliq',
        ArabicName: 'اﻟﺨَﺎﻟِﻖ.',
        meaning: 'The Creator of Everything',
        evidence: '',
    },
    {
        EnglishName: 'Al Khallaaq',
        ArabicName: 'اﻟﺨَﻼ ﻕ ',
        meaning: ' The Creator Who Creates Again & Again',
        evidence: '',
    },
    {
        EnglishName: 'Ar-Ra’oof',
        ArabicName: 'اﻟﺮَّﺅُﻭﻑ  ',
        meaning: 'The Compassionate',
        evidence: '',
    },
    {
        EnglishName: 'Ar-Rahmaan',
        ArabicName: 'اﻟﺮَّﺣْﻤَﺎﻥ.',
        meaning: 'The Extremely Merciful',
        evidence: '',
    },
    {
        EnglishName: 'Ar-Raheem',
        ArabicName: 'اﻟﺮَّﺣِﻴﻢ',
        meaning: 'The Bestower of Mercy',
        evidence: '',
    },
    {
        EnglishName: 'Ar-Razzaaq',
        ArabicName: 'اﻟﺮَّﺯَّاﻕ ',
        meaning: 'The Great Provider',
        evidence: '',
    },
    {
        EnglishName: 'Ar-Raqeeb',
        ArabicName: 'اﻟﺮَّﻗِﻴﺐ',
        meaning: 'The Watchful',
        evidence: '',
    },
    {
        EnglishName: 'As-Salaam',
        ArabicName: 'ﺳﻼﻡ ',
        meaning: 'The Flawless One',
        evidence: '',
    },
    {
        EnglishName: 'As Samee',
        ArabicName: ' اﻟﺴَّﻤِﻴﻊ',
        meaning: 'The All Hearing',
        evidence: '',
    },
    {
        EnglishName: 'Ash-Shaakir',
        ArabicName: ' اﻟﺸَﺎﻛِﺮ',
        meaning: 'The Grateful',
        evidence: '',
    },
    {
        EnglishName: 'Ash-Shakoor',
        ArabicName: 'ﻟﺸَّﻜُﻮﺭ ',
        meaning: 'The Appreciative',
        evidence: '',
    },
    {
        EnglishName: 'Ash-Shaheed',
        ArabicName: ' اﻟﺸَّﻬِﻴﺪ',
        meaning: 'The Witness',
        evidence: '',
    },
    {
        EnglishName: 'As-Samad ',
        ArabicName: 'اﻟﺼَّﻤَﺪ ',
        meaning: 'The Perfect Lord & Master Upon Whom All of the Creation Depends',
        evidence: '',
    },
    {
        EnglishName: 'Al-`Aalim',
        ArabicName: 'اﻟﻌﻠﻴﻢ ',
        meaning: 'The All Knower',
        evidence: '',
    },
    {
        EnglishName: 'Al-`Azeez ',
        ArabicName: 'اﻟﻌﺰﻳﺰ ',
        meaning: 'The Almighty',
        evidence: '',
    },
    {
        EnglishName: 'Al-Adheem ',
        ArabicName: 'العَظِيم    ',
        meaning: '',
        evidence: '',
    },
    {
        EnglishName: 'Al-`Afuww',
        ArabicName: 'ااﻟﻌﻔﻮ',
        meaning: 'The One Who Pardons Again & Again',
        evidence: '',
    },
    {
        EnglishName: 'Al-`Aliyy',
        ArabicName: 'العَلِيّ',
        meaning: 'The Sublime',
        evidence: '',
    },
    {
        EnglishName: 'Al-Ghaffaar',
        ArabicName: 'اﻟﻐﻔﻮﺭ ',
        meaning: 'The Oft-Forgiving',
        evidence: '',
    },
    {
        EnglishName: 'Al-Ghafoor',
        ArabicName: 'اﻟﻐَﻔُﻮﺭ ',
        meaning: 'The One Who Forgives Extensively',
        evidence: '',
    },
    {
        EnglishName: 'Al-Ghaniyy',
        ArabicName: 'اﻟﻐﻨﻲ ',
        meaning: 'The Self Sufficient',
        evidence: '',
    },
    {
        EnglishName: 'Al-Fattaah',
        ArabicName: 'اﻟﻔﺘﺎﺡ ',
        meaning: 'The Opener/Arbiter',
        evidence: '',
    },
    {
        EnglishName: 'Al-Qaadir',
        ArabicName: 'اﻟﻘَﺎﺩِﺭ ',
        meaning: 'The Fully Able One',
        evidence: '',
    },
    {
        EnglishName: 'Al-Qaahir',
        ArabicName: ' القَاهِر',
        meaning: 'The Subduer/Subjugator',
        evidence: '',
    },

    {
        EnglishName: 'Al-Quddoos',
        ArabicName: 'ٱلْقُدُّوسُ  ',
        meaning: 'The Pure & Perfect',
        evidence: '',
    },
    {
        EnglishName: 'Al-Qadeer',
        ArabicName: 'القَدِير ',
        meaning: 'The All Powerful',
        evidence: '',
    },
    {
        EnglishName: 'Al-Qareeb',
        ArabicName: 'القَرِيب ',
        meaning: 'The Ever Near',
        evidence: '',
    },
    {
        EnglishName: 'Al-Qawiyy',
        ArabicName: '  ٱلْقَوِيُّ',
        meaning: ' The Strong',
        evidence: '',
    },

    {
        EnglishName: 'Al-Qahhaar',
        ArabicName: ' القَهَّار',
        meaning: 'The Subjugator',
        evidence: '',
    },
    {
        EnglishName: 'Al-Kabeer',
        ArabicName: 'الكَبِير ',
        meaning: 'The Magnificent/Grand',
        evidence: '',
    },
    {
        EnglishName: 'Al-Kareem',
        ArabicName: 'اﻟﻜﺮﻳﻢ ',
        meaning: 'The Most Noble & Generous',
        evidence: '',
    },
    {
        EnglishName: 'Al-Lateef ',
        ArabicName: 'اﻟﻠﻄﻴﻒ ',
        meaning: 'The Subtle & Kind',
        evidence: '',
    },
    {
        EnglishName: 'Al-Mu`min',
        ArabicName: 'اﻟﻤﺆﻣﻦ ',
        meaning: ' The Trustworthy Granter of Security',
        evidence: '',
    },

    {
        EnglishName: 'Al-Muta’aalee',
        ArabicName: ' اﻟﻤﺘﻌﺎﻟﻲ',
        meaning: ' The Supreme',
        evidence: '',
    },
    {
        EnglishName: 'Al-Mutakabbir',
        ArabicName: 'اﻟﻤﺘﻜﺒﺮ ',
        meaning: 'The Justly & Rightfully Proud',
        evidence: '',
    },

    {
        EnglishName: 'Al-Mateen',
        ArabicName: 'اﻟﻤﺘﻴﻦ ',
        meaning: ' The Firm One',
        evidence: '',
    },
    {
        EnglishName: 'Al-Mujeeb',
        ArabicName: 'اﻟﻤﺠﻴﺐ ',
        meaning: ' The Responsive',
        evidence: '',
    },
    {
        EnglishName: 'Al-Majeed',
        ArabicName: 'اﻟﻤﺠﻴﺪ ',
        meaning: 'The Glorious',
        evidence: '',
    },
    {
        EnglishName: 'Al-Muheet',
        ArabicName: 'اﻟﻤﺤﻴﻂ ',
        meaning: ' The All Encompassing',
        evidence: '',
    },

    {
        EnglishName: 'Al-Musawwir',
        ArabicName: 'اﻟﻤﺼﻮﺭ ',
        meaning: 'The Bestower of Forms',
        evidence: '',
    },
    {
        EnglishName: 'Al-Muqtadir',
        ArabicName: ' اﻟﻤﻘﺘﺪﺭ',
        meaning: 'The All Powerful Maintainer',
        evidence: '',
    },
    {
        EnglishName: 'Al-Malik',
        ArabicName: 'اﻟﻤﻠﻚ ',
        meaning: ' The King',
        evidence: '',
    },
    {
        EnglishName: 'Al-Maleek',
        ArabicName: 'اﻟﻤﻠﻴﻚ ',
        meaning: ' The Supreme Sovereign',
        evidence: '',
    },
    {
        EnglishName: 'Al-Mawlaa',
        ArabicName: 'اﻟﻤﻮﻟﻰ ',
        meaning: ' The Master',
        evidence: '',
    },
    {
        EnglishName: 'Al-Muhaymin',
        ArabicName: 'اﻟﻤﻬﻴﻤﻦ ',
        meaning: 'The Dominant One',
        evidence: '',
    },
    {
        EnglishName: 'An-Naseer',
        ArabicName: 'اﻟﻨﺼﻴﺮ ',
        meaning: ' The Helper',
        evidence: '',
    },
    {
        EnglishName: 'Al-Waahid',
        ArabicName: ' اﻟﻮاﺣﺪ',
        meaning: ' The One & Only',
        evidence: '',
    },
    {
        EnglishName: 'Al-Waarith',
        ArabicName: 'اﻟﻮاﺭﺙ ',
        meaning: 'The Inheritor',
        evidence: '',
    },
    {
        EnglishName: 'Al Waasi',
        ArabicName: 'اﻟﻮاﺳﻊ ',
        meaning: ' The Vast One',
        evidence: '',
    },
    {
        EnglishName: 'Al-Wadood',
        ArabicName: ' اﻟﻮﺩﻭﺩ',
        meaning: ' The Loving',
        evidence: '',
    },
    {
        EnglishName: 'Al-Wakeel',
        ArabicName: ' اﻟﻮﻛﻴﻞ',
        meaning: ' The Trustee',
        evidence: '',
    },
    {
        EnglishName: 'Al-Waliyy',
        ArabicName: 'اﻟﻮﻟﻲ ',
        meaning: 'The Guardian',
        evidence: '',
    },
    {
        EnglishName: 'Al-Wahhaab',
        ArabicName: 'اﻟﻮﻫﺎﺏ ',
        meaning: 'The Bestower',
        evidence: '',
    },
    {
        EnglishName: 'Al-Jameel',
        ArabicName: 'اﻟﺠﻤﻴﻞ ',
        meaning: 'The Beautiful',
        evidence: '',
    },
    {
        EnglishName: 'Al-Jawaad',
        ArabicName: 'اﻟﺠﻮاﺩ ',
        meaning: 'The Munificent',
        evidence: '',
    },
    {
        EnglishName: 'Al-Hakam',
        ArabicName: ' اﻟﺤﻜﻢ',
        meaning: 'The Judge',
        evidence: '',
    },
    {
        EnglishName: 'Al-Hayyiyu',
        ArabicName: '  الحَيي',
        meaning: 'The Modest',
        evidence: '',
    },
    {
        EnglishName: 'Ar-Rabb',
        ArabicName: 'اﻟﺮﺏ ',
        meaning: ' The Lord and Nurturer',
        evidence: '',
    },
    {
        EnglishName: 'Ar-Rafeeq',
        ArabicName: 'اﻟﺮﻓﻴﻖ ',
        meaning: 'The Gentle',
        evidence: '',
    },
    {
        EnglishName: 'As-Subbooh',
        ArabicName: 'اﻟﺴﺒﻮﺡ ',
        meaning: 'The Perfect',
        evidence: '',
    },
    {
        EnglishName: 'As-Sayyid',
        ArabicName: 'اﻟﺴﻴﺪ ',
        meaning: 'The Lord & Master',
        evidence: '',
    },
    {
        EnglishName: 'Ash-Shaafee',
        ArabicName: 'اﻟﺸﺎﻓﻲ ',
        meaning: 'The Healer',
        evidence: '',
    },
    {
        EnglishName: 'At-Tayyib',
        ArabicName: 'اﻟﻄﻴﺐ ',
        meaning: 'The Pure One',
        evidence: '',
    },
    {
        EnglishName: 'Al-Qaabid',
        ArabicName: 'اﻟﻘﺎﺑﺾ ',
        meaning: 'The Withholder',
        evidence: '',
    },
    {
        EnglishName: 'Al-Baasit',
        ArabicName: 'اﻟﺒﺎﺳﻂ ',
        meaning: 'The Expander',
        evidence: '',
    },
    {
        EnglishName: 'Al-Muqaddim',
        ArabicName: 'اﻟﻤﻘﺪﻡ ',
        meaning: 'The One Who Gives Precedence',
        evidence: '',
    },
    {
        EnglishName: 'Al-Mu`akhkhir',
        ArabicName: ' اﻟﻤﺆﺧﺮ',
        meaning: 'The Delayer',
        evidence: '',
    },
    {
        EnglishName: 'Al-Muhsin',
        ArabicName: 'اﻟﻤﺤﺴﻦ ',
        meaning: 'The Benevolent',
        evidence: '',
    },
    {
        EnglishName: 'Al Mu’tee',
        ArabicName: 'اﻟﻤﻌﻄﻲ ',
        meaning: 'The Giver',
        evidence: '',
    },
    {
        EnglishName: 'Al-Mannaan',
        ArabicName: 'اﻟﻤﻨﺎﻥ ',
        meaning: 'The Benefactor',
        evidence: '',
    },
    {
        EnglishName: 'Al-Witr',
        ArabicName: 'اﻟﻮﺗﺮ ',
        meaning: 'The One',
        evidence: '',
    },
];
export default store99names;